### ISSUE TITLE
Data to set the cutoff score?

### ISSUE THREAD

**Issue by ashwinssudarshan** [SDmetagenomics/Angelo2018_Paper#1]
Hey, I was trying to replicate the steps you used to create the rpS3 HMM and was wondering if you had the data(Uniprot reference proteomes) that was used to get the cutoff score which is given as the graph in the folder?

Did you just pick all the reference proteomes on the mentioned date and run it through the HMM to get the cutoffs?

If you could mention any additional modification steps used to get the test data to set the cutoff, it would be very helpful. Thank you!!

**Comment by SDmetagenomics** [comment]
Yes, all non-eukaryotic proteomes from uniprot reference proteomes from the date mentioned were used. Unfortunately I don't think I can upload the exact dataset to github since it is quite large. It would be fine to just download the current uniprot reference proteomes tho. 

Also I am still a bit unclear on what you are trying to do. If you are trying to create an rpS3 HMM, please see our manuscript and the methods as it is detailed there. If you are more concenrend with generating an HMM cutoff score, that was done manually at the score that I felt very few if any non-rpS3 sequences would be higher than against the tested HMM. The plot is provided to illustrate where that score falls across all scores generated by the HMM when scored against the uniprot reference proteomes database.

**Comment by ashwinssudarshan** [comment]
Thank you so much for your help, Spencer! I was mainly trying to understand as to how the cutoff was decided and your reply clarified it.
